export const LanguageList = [
  { value: "ar", name: "Arabic" },
  { value: "de", name: "German" },
  { value: "en", name: "English" },
  { value: "es", name: "Spanish" },
  { value: "et", name: "Estonian" },
  { value: "fr", name: "French" },
  { value: "id", name: "Indonesian" },
  { value: "it", name: "Italian" },
  { value: "ja", name: "Japanese" },
  { value: "ko", name: "Korean" },
  { value: "nl", name: "Dutch" },
  { value: "pl", name: "Polish" },
  { value: "pt-br", name: "Portuguese (Brazil)" },
  { value: "pt", name: "Portuguese (European)" },
  { value: "ro", name: "Romanian" },
  { value: "ru", name: "Russian" },
  { value: "th", name: "Thai" },
  { value: "tr", name: "Turkish" },
  { value: "zh-CN", name: "Chinese (Simplified)" },
  { value: "zh-HK", name: "Chinese (Hong Kong)" },
  { value: "zh-SG", name: "Chinese (Singapore)" },
  { value: "zh-TW", name: "Chinese (Traditional)" },
  { value: "zh", name: "Chinese (Singapore)" },
];
